version: "3"

services:
  graphql:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/app
    ports:
      - 9000:3000
    networks:
      - agenda
      - autenticacao

networks:
  agenda:
    external:
      name: agenda
  autenticacao:
    external:
      name: autenticacao
