version: "2"

services:
  graphql:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/app
    ports:
      - 9000:3000
    environment:
      MONGODB_URI: mongodb://root:root@db/agenda
    networks:
      - agenda

networks:
  agenda:
    external:
      name: agenda
